'''
Problem 12
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''

def triangular_number(n):
    return(n ** 2 + n)//2



def list_factors(n):
    # factors = []
    # for x in range(1,n+1):
    #     if n % x == 0:
    #         factors.append(x)
    factors = [x for x in range(1,n+1) if n % x == 0]

    return factors

def main():
    # for x in range(1000,2000,2):
    #     num = triangular_number(x)
    #     print(list_factors(num))
    #     if len(list_factors(num)) > 500:
    #         print(f"{num} has over five hundred divisors!")

    for i in list(map(triangular_number, range(1000,2000,2))):
        if len(list_factors(i)) > 500:
            print(list_factors(i))
    print("N/A")

    print(len(list_factors(list(map(triangular_number, range(1000,2000,2))))))



if __name__ == '__main__':
    main()